# Generated by Django 2.0.2 on 2018-04-17 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('derpartmentname', models.CharField(default='默认部门', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DutyInfo',
            fields=[
                ('duid', models.AutoField(primary_key=True, serialize=False)),
                ('dutyname', models.CharField(default='主班', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dutyschedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dutydate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='R_DepartmentInfo_DutyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.DepartmentInfo')),
                ('duid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.DutyInfo')),
            ],
        ),
        migrations.CreateModel(
            name='R_UserInfo_DepartmentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.DepartmentInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='值班员', max_length=20)),
                ('isdel', models.BooleanField()),
                ('createdate', models.DateField(auto_now_add=True)),
                ('modeificateddate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='r_userinfo_departmentinfo',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.UserInfo'),
        ),
    ]
