# Generated by Django 2.0.4 on 2018-08-28 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='duty_dutyDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='auth用户')),
            ],
        ),
        migrations.CreateModel(
            name='DutyScheduleMidModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dutydate', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DutyScheduleProxyModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('duty.dutyschedule',),
        ),
        migrations.AlterModelOptions(
            name='departmentinfo',
            options={'verbose_name': '部门信息', 'verbose_name_plural': '部门信息'},
        ),
        migrations.AlterModelOptions(
            name='dutyinfo',
            options={'verbose_name': '值班类别', 'verbose_name_plural': '值班类别'},
        ),
        migrations.AlterModelOptions(
            name='r_departmentinfo_dutyinfo',
            options={'verbose_name': '部门与岗位关系', 'verbose_name_plural': '部门与岗位关系'},
        ),
        migrations.AlterModelOptions(
            name='r_userinfo_departmentinfo',
            options={'verbose_name': '人员与部门关系', 'verbose_name_plural': '人员与部门关系'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='dutyinfo',
            name='createdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyinfo',
            name='isdel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dutyinfo',
            name='modeificateddate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='rDepartmentDuty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='duty.R_DepartmentInfo_DutyInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='duty.UserInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dutyschedule',
            name='dutydate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='createdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='isdel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='modeificateddate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyschedulemidmodel',
            name='rDepartmentDuty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.R_DepartmentInfo_DutyInfo'),
        ),
        migrations.AddField(
            model_name='dutyschedulemidmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.UserInfo'),
        ),
        migrations.AddField(
            model_name='duty_dutydepartment',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.DepartmentInfo', verbose_name='部门'),
        ),
    ]
